apiDir: "../zain-headless-userorder-list-api/src/main/java"
apiPackagePath: "zain.headless.userorder.list"
application:
    baseURI: "/zain-headless-userorder-list"
    className: "ZainHeadlessUserorderListApplication"
    name: "ZainHeadlessUserorderList"
author: "User"
clientDir: "../zain-headless-userorder-list-client/src/main/java"
testDir: "../zain-headless-userorder-list-test/src/testIntegration/java"